### ISSUE TITLE
Flutter Linting

### ISSUE THREAD

**Issue by nooralibutt** [nooralibutt/playon#1]
Integrate flutter lints

https://pub.dev/packages/flutter_lints

**Comment by rmahmadkhan** [comment]
Add this code to `analysis_options.yaml` in the project after adding the package

```
# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at
  # https://dart-lang.github.io/linter/lints/index.html.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
   always_use_package_imports: true
   avoid_dynamic_calls: true
   avoid_empty_else: true
   # When we implement logger package we will mark it as true
   avoid_print: false
   avoid_relative_lib_imports: true
   avoid_returning_null_for_future: true
   avoid_type_to_string: true
   avoid_types_as_parameter_names: ture
   comment_references: true
   control_flow_in_finally: true
   empty_statements: true
   prefer_single_quotes: true
   use_named_constants: true
   use_to_and_as_if_applicable: true
   use_string_buffers: true
   use_late_for_private_fields_and_variables: true
   use_is_even_rather_than_modulo: true
   use_if_null_to_convert_nulls_to_bools: true
   use_function_type_syntax_for_parameters: true
   use_full_hex_values_for_flutter_colors: true
   unnecessary_this: true
   void_checks: true
   cancel_subscriptions: true
   close_sinks: true
   always_declare_return_types: true
   always_put_required_named_parameters_first: true
   always_require_non_null_named_parameters: true
   annotate_overrides: true
   avoid_bool_literals_in_conditional_expressions: true
   avoid_catches_without_on_clauses: true
   avoid_double_and_int_checks: true
   constant_identifier_names: true
   prefer_final_locals: true
   prefer_final_fields: true
   camel_case_types: true
   flutter_style_todos: true
   prefer_const_declarations: true
   prefer_const_constructors_in_immutables: true
   prefer_contains: true
   prefer_is_empty: true
   prefer_is_not_empty: true
   prefer_is_not_operator: true
   prefer_iterable_whereType: true
   prefer_mixin: true
   prefer_null_aware_method_calls: true
   prefer_null_aware_operators: true
   prefer_spread_collections: true
   prefer_typing_uninitialized_variables: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
```
